import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
    drv_at25df641.c
    """)

group = DefineGroup('Drives', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
